apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata: 
  name: aiops-k8s
spec:
  version: 8.5.2
  #version: 8.0.0
  #version: 8.0.0-rc2
  #version: 7.16.2
  kibanaRef:
    name: aiops
  fleetServerRef: 
    name: aiops-fleet
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: aiops-k8s
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aiops-k8s
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - namespaces
  - events
  - services
  - configmaps
  verbs:
  - get
  - watch
  - list
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
- apiGroups: ["extensions"]
  resources:
    - replicasets
  verbs: 
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - "get"
  - "list"
  - "watch"
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - "get"
  - "list"
  - "watch"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aiops-k8s
  namespace: es
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aiops-k8s
subjects:
- kind: ServiceAccount
  name: aiops-k8s
  namespace: es
roleRef:
  kind: ClusterRole
  name: aiops-k8s
  apiGroup: rbac.authorization.k8s.io